services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dale
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/dale?schema=public"
      JWT_SECRET: "cambia_este_secreto"
    command: npm run start  # o el comando que uses para prod

volumes:
  db_data:
